name: Bulk Pitch Repertoire Submission
description: Submit pitch repertoires for multiple pitchers at once
title: "[Pitch Bulk] "
labels: ["pitch-repertoire", "enhancement", "bulk"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bulk Pitch Repertoire Submission
        Submit multiple pitcher repertoires at once!

        **Format:** `Player Name | Pitch1, Pitch2, Pitch3, ...`

        List pitches in order of usage (primary pitch first).

        **Available pitches:** Fastball, Slider, Curve, Changeup, Splitter, Forkball, Sinker, Cutter, Knuckleball, KnuckleCurve, CircleChange, Screwball
  - type: textarea
    id: pitches
    attributes:
      label: Pitch Repertoires
      description: "Format: Player Name | Pitch1, Pitch2, ... (one player per line)"
      placeholder: |
        Yu Darvish | Fastball, Slider, Curve, Splitter, Changeup
        Masahiro Tanaka | Fastball, Splitter, Slider, Curve
        Shohei Ohtani | Fastball, Slider, Splitter, Curve
        Koji Uehara | Fastball, Splitter
      render: text
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      placeholder: "Any additional context"
    validations:
      required: false
