name: Pitch Repertoire
description: Submit pitch repertoire information for a pitcher
title: "[Pitch] "
labels: ["pitch-repertoire", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Pitch Repertoire Project
        Help us build accurate pitch repertoires for NPB pitchers!
  - type: input
    id: player_name
    attributes:
      label: Player Name
      description: Pitcher's name (English or Japanese)
      placeholder: "e.g., Yu Darvish / ダルビッシュ有"
    validations:
      required: true
  - type: input
    id: player_id
    attributes:
      label: Player ID (if known)
      placeholder: "e.g., darvish01"
    validations:
      required: false
  - type: dropdown
    id: pitch1
    attributes:
      label: "1st Pitch (Primary)"
      options:
        - Fastball
        - Slider
        - Curve
        - Changeup
        - Splitter
        - Forkball
        - Sinker
        - Cutter
        - Knuckleball
        - KnuckleCurve
        - CircleChange
        - Screwball
    validations:
      required: true
  - type: dropdown
    id: pitch2
    attributes:
      label: "2nd Pitch"
      options:
        - (None)
        - Fastball
        - Slider
        - Curve
        - Changeup
        - Splitter
        - Forkball
        - Sinker
        - Cutter
        - Knuckleball
        - KnuckleCurve
        - CircleChange
        - Screwball
    validations:
      required: false
  - type: dropdown
    id: pitch3
    attributes:
      label: "3rd Pitch"
      options:
        - (None)
        - Fastball
        - Slider
        - Curve
        - Changeup
        - Splitter
        - Forkball
        - Sinker
        - Cutter
        - Knuckleball
        - KnuckleCurve
        - CircleChange
        - Screwball
    validations:
      required: false
  - type: dropdown
    id: pitch4
    attributes:
      label: "4th Pitch"
      options:
        - (None)
        - Fastball
        - Slider
        - Curve
        - Changeup
        - Splitter
        - Forkball
        - Sinker
        - Cutter
        - Knuckleball
        - KnuckleCurve
        - CircleChange
        - Screwball
    validations:
      required: false
  - type: dropdown
    id: pitch5
    attributes:
      label: "5th Pitch"
      options:
        - (None)
        - Fastball
        - Slider
        - Curve
        - Changeup
        - Splitter
        - Forkball
        - Sinker
        - Cutter
        - Knuckleball
        - KnuckleCurve
        - CircleChange
        - Screwball
    validations:
      required: false
  - type: dropdown
    id: pitch6
    attributes:
      label: "6th Pitch"
      options:
        - (None)
        - Fastball
        - Slider
        - Curve
        - Changeup
        - Splitter
        - Forkball
        - Sinker
        - Cutter
        - Knuckleball
        - KnuckleCurve
        - CircleChange
        - Screwball
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      placeholder: "e.g., Fastball tops out at 160 km/h"
    validations:
      required: false
  - type: input
    id: source
    attributes:
      label: Source (optional)
      placeholder: "e.g., YouTube, NPB broadcast"
    validations:
      required: false
